<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Admin API</title>
    <link rel="stylesheet" type="text/css" href="https://admin-api.docs.keitaro.io/swagger-ui/swagger-ui.css" >
    <link rel="icon" type="image/png" href="/admin/favicon.png" />
    <style>
        html
        {
            box-sizing: border-box;
            overflow: -moz-scrollbars-vertical;
            overflow-y: scroll;
        }

        *,
        *:before,
        *:after
        {
            box-sizing: inherit;
        }

        body
        {
            margin:0;
            background: #fafafa;
        }
    </style>
</head>

<body>
<div id="swagger-ui"></div>

<script src="https://admin-api.docs.keitaro.io/swagger-ui/swagger-ui-bundle.js"> </script>
<script src="https://admin-api.docs.keitaro.io/swagger-ui/swagger-ui-standalone-preset.js"> </script>e
<link rel="stylesheet" href="https://admin-api.docs.keitaro.io/assets/theme-keitaro.css">
<script>
  window.onload = function() {
    // Begin Swagger UI call region
    const ui = SwaggerUIBundle({
      spec: location.host,
      url: "?object=adminApi.spec",
      dom_id: '#swagger-ui',
      deepLinking: true,
      presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIStandalonePreset
      ],
      plugins: [
      ],
      layout: "StandaloneLayout",
    })
    window.ui = ui
  }
</script>
</body>
</html>