<?php
 return array (
  'Badakhshan' => 'BDS',
  'Badghis' => 'BDG',
  'Baghlan' => 'BGL',
  'Balkh' => 'BAL',
  'Bamyan' => 'BAM',
  'Daykundi' => 'DAY',
  'Farah' => 'FRA',
  'Faryab' => 'FYB',
  'Ghazni' => 'GHA',
  'Ghor' => 'GHO',
  'Helmand' => 'HEL',
  'Herat' => 'HER',
  'Jowzjan' => 'JOW',
  'Kabul' => 'KAB',
  'Kandahar' => 'KAN',
  'Kapisa' => 'KAP',
  'Khost' => 'KHO',
  'Kunar' => 'KNR',
  'Kunduz' => 'KDZ',
  'Laghman' => 'LAG',
  'Logar' => 'LOG',
  'Nangarhar' => 'NAN',
  'Nimroz' => 'NIM',
  'Nuristan' => 'NUR',
  'Paktika' => 'PKA',
  'Paktiya' => 'PIA',
  'Panjshayr' => 'PAN',
  'Parwan' => 'PAR',
  'Samangan' => 'SAM',
  'Sar-e Pul' => 'SAR',
  'Takhar' => 'TAK',
  'Uruzgan' => 'URU',
  'Wardak' => 'WAR',
  'Zabul' => 'ZAB',
);