<?php
 return array (
  'Buenos Aires' => '0B',
  'Catamarca' => '0K',
  'Chaco' => '0H',
  'Chubut' => '0U',
  'Ciudad Autonoma de Buenos Aires' => '0C',
  'Cordoba' => '0X',
  'Corrientes' => '0W',
  'Entre Rios' => '0E',
  'Formosa' => '0P',
  'Jujuy' => '0Y',
  'La Pampa' => '0L',
  'La Rioja' => '0F',
  'Mendoza' => '0M',
  'Misiones' => '0N',
  'Neuquen' => '0Q',
  'Rio Negro' => '0R',
  'Salta' => '0A',
  'San Juan' => '0J',
  'San Luis' => '0D',
  'Santa Cruz' => '0Z',
  'Santa Fe' => '0S',
  'Santiago del Estero' => '0G',
  'Tierra del Fuego' => '0V',
  'Tucuman' => '0T',
);