<?php
 return array (
  'Bas-Uele' => 'BU',
  'Equateur' => 'EQ',
  'Haut-Katanga' => 'HK',
  'Haut-Lomani' => 'HL',
  'Haut-Uele' => 'HU',
  'Ituri' => 'IT',
  'Kasai' => 'KS',
  'Kasai Central' => 'KC',
  'Kasai Oriental' => 'KE',
  'Kinshasa' => 'KN',
  'Kongo Central' => 'BC',
  'Kwango' => 'KG',
  'Kwilu' => 'KL',
  'Lomami' => 'LO',
  'Lualaba' => 'LU',
  'Mai-Ndombe' => 'MN',
  'Maniema' => 'MA',
  'Mongala' => 'MO',
  'Nord-Kivu' => 'NK',
  'Nord-Ubangi' => 'NU',
  'Sankuru' => 'SA',
  'Sud-Kivu' => 'SK',
  'Sud-Ubangi' => 'SU',
  'Tanganyika' => 'TA',
  'Tshopo' => 'TO',
  'Tshuapa' => 'TU',
);