<?php
 return array (
  'Aargau' => 'AG',
  'Appenzell Ausserrhoden' => 'AR',
  'Appenzell Innerrhoden' => 'AI',
  'Basel-Landschaft' => 'BL',
  'Basel-Stadt' => 'BS',
  'Bern' => 'BE',
  'Fribourg' => 'FR',
  'Geneve' => 'GE',
  'Glarus' => 'GL',
  'Graubunden' => 'GR',
  'Jura' => 'JU',
  'Luzern' => 'LU',
  'Neuchatel' => 'NE',
  'Nidwalden' => 'NW',
  'Obwalden' => 'OW',
  'Sankt Gallen' => 'SG',
  'Schaffhausen' => 'SH',
  'Schwyz' => 'SZ',
  'Solothurn' => 'SO',
  'Thurgau' => 'TG',
  'Ticino' => 'TI',
  'Uri' => 'UR',
  'Valais' => 'VS',
  'Vaud' => 'VD',
  'Zug' => 'ZG',
  'Zurich' => 'ZH',
);