<?php
 return array (
  'Anhui' => '34',
  'Beijing' => '11',
  'Chongqing' => '50',
  'Fujian' => '35',
  'Gansu' => '62',
  'Guangdong' => '44',
  'Guangxi' => '45',
  'Guizhou' => '52',
  'Hainan' => '46',
  'Hebei' => '13',
  'Heilongjiang' => '23',
  'Henan' => '41',
  'Hubei' => '42',
  'Hunan' => '43',
  'Jiangsu' => '32',
  'Jiangxi' => '36',
  'Jilin' => '22',
  'Liaoning' => '21',
  'Nei Mongol' => '15',
  'Ningxia' => '64',
  'Qinghai' => '63',
  'Shaanxi' => '61',
  'Shandong' => '37',
  'Shanghai' => '31',
  'Shanxi' => '14',
  'Sichuan' => '51',
  'Tianjin' => '12',
  'Xinjiang' => '65',
  'Xizang' => '54',
  'Yunnan' => '53',
  'Zhejiang' => '33',
);