<?php
 return array (
  'Amazonas' => 'AMA',
  'Antioquia' => 'ANT',
  'Arauca' => 'ARA',
  'Atlantico' => 'ATL',
  'Bolivar' => 'BOL',
  'Boyaca' => 'BOY',
  'Caldas' => 'CAL',
  'Caqueta' => 'CAQ',
  'Casanare' => 'CAS',
  'Cauca' => 'CAU',
  'Cesar' => 'CES',
  'Choco' => 'CHO',
  'Cordoba' => 'COR',
  'Cundinamarca' => 'CUN',
  'Distrito Capital de Bogota' => 'DC',
  'Guainia' => 'GUA',
  'Guaviare' => 'GUV',
  'Huila' => 'HUI',
  'La Guajira' => 'LAG',
  'Magdalena' => 'MAG',
  'Meta' => 'MET',
  'Narino' => 'NAR',
  'Norte de Santander' => 'NSA',
  'Putumayo' => 'PUT',
  'Quindio' => 'QUI',
  'Risaralda' => 'RIS',
  'San Andres, Providencia y Santa Catalina' => 'SAP',
  'Santander' => 'SAN',
  'Sucre' => 'SUC',
  'Tolima' => 'TOL',
  'Valle del Cauca' => 'VAC',
  'Vaupes' => 'VAU',
  'Vichada' => 'VID',
);