<?php
 return array (
  'Boa Vista' => 'BV',
  'Brava' => 'BR',
  'Maio' => 'MA',
  'Mosteiros' => 'MO',
  'Paul' => 'PA',
  'Porto Novo' => 'PN',
  'Praia' => 'PR',
  'Ribeira Brava' => 'RB',
  'Ribeira Grande' => 'RG',
  'Ribeira Grande de Santiago' => 'RS',
  'Sal' => 'SL',
  'Santa Catarina' => 'CA',
  'Santa Catarina do Fogo' => 'CF',
  'Santa Cruz' => 'CR',
  'Sao Domingos' => 'SD',
  'Sao Filipe' => 'SF',
  'Sao Miguel' => 'SM',
  'Sao Salvador do Mundo' => 'SS',
  'Sao Vicente' => 'SV',
  'Tarrafal' => 'TA',
  'Tarrafal de Sao Nicolau' => 'TS',
);