<?php
 return array (
  'Azua' => '02',
  'Baoruco' => '03',
  'Barahona' => '04',
  'Dajabon' => '05',
  'Distrito Nacional (Santo Domingo)' => '01',
  'Duarte' => '06',
  'El Seibo' => '08',
  'Elias Pina' => '07',
  'Espaillat' => '09',
  'Hato Mayor' => '30',
  'Hermanas Mirabal' => '19',
  'Independencia' => '10',
  'La Altagracia' => '11',
  'La Romana' => '12',
  'La Vega' => '13',
  'Maria Trinidad Sanchez' => '14',
  'Monsenor Nouel' => '28',
  'Monte Cristi' => '15',
  'Monte Plata' => '29',
  'Pedernales' => '16',
  'Peravia' => '17',
  'Puerto Plata' => '18',
  'Samana' => '20',
  'San Cristobal' => '21',
  'San Juan' => '22',
  'San Pedro de Macoris' => '23',
  'Sanchez Ramirez' => '24',
  'Santiago' => '25',
  'Santiago Rodriguez' => '26',
  'Valverde' => '27',
);