<?php
 return array (
  'Azuay' => '0A',
  'Bolivar' => '0B',
  'Canar' => '0F',
  'Carchi' => '0C',
  'Chimborazo' => '0H',
  'Cotopaxi' => '0X',
  'El Oro' => '0O',
  'Esmeraldas' => '0E',
  'Galapagos' => '0W',
  'Guayas' => '0G',
  'Imbabura' => '0I',
  'Loja' => '0L',
  'Los Rios' => '0R',
  'Manabi' => '0M',
  'Morona-Santiago' => '0S',
  'Napo' => '0N',
  'Orellana' => '0D',
  'Pastaza' => '0Y',
  'Pichincha' => '0P',
  'Santa Elena' => 'SE',
  'Sucumbios' => '0U',
  'Tungurahua' => '0T',
  'Zamora-Chinchipe' => '0Z',
);