<?php
 return array (
  'Ad Daqahliyah' => 'DK',
  'Al Bahr al Ahmar' => 'BA',
  'Al Buhayrah' => 'BH',
  'Al Fayyum' => 'FYM',
  'Al Gharbiyah' => 'GH',
  'Al Iskandariyah' => 'ALX',
  'Al Isma\'iliyah' => 'IS',
  'Al Jizah' => 'GZ',
  'Al Minufiyah' => 'MNF',
  'Al Minya' => 'MN',
  'Al Qahirah' => '0C',
  'Al Qalyubiyah' => 'KB',
  'Al Uqsur' => 'LX',
  'Al Wadi al Jadid' => 'WAD',
  'As Suways' => 'SUZ',
  'Ash Sharqiyah' => 'SHR',
  'Aswan' => 'ASN',
  'Asyut' => 'AST',
  'Bani Suwayf' => 'BNS',
  'Bur Sa\'id' => 'PTS',
  'Dumyat' => 'DT',
  'Janub Sina\'' => 'JS',
  'Kafr ash Shaykh' => 'KFS',
  'Matruh' => 'MT',
  'Qina' => 'KN',
  'Shamal Sina\'' => 'SIN',
  'Suhaj' => 'SHG',
);