<?php
 return array (
  'Andalucia' => 'AN',
  'Aragon' => 'AR',
  'Asturias, Principado de' => 'AS',
  'Canarias' => 'CN',
  'Cantabria' => 'CB',
  'Castilla y Leon' => 'CL',
  'Castilla-La Mancha' => 'CM',
  'Catalunya' => 'CT',
  'Ceuta' => 'CE',
  'Extremadura' => 'EX',
  'Galicia' => 'GA',
  'Illes Balears' => 'IB',
  'La Rioja' => 'RI',
  'Madrid, Comunidad de' => 'MD',
  'Melilla' => 'ML',
  'Murcia, Region de' => 'MC',
  'Navarra, Comunidad Foral de' => 'NC',
  'Pais Vasco' => 'PV',
  'Valenciana, Comunidad' => 'VC',
);