<?php
 return array (
  'Etela-Karjala' => '02',
  'Etela-Pohjanmaa' => '03',
  'Etela-Savo' => '04',
  'Kainuu' => '05',
  'Kanta-Hame' => '06',
  'Keski-Pohjanmaa' => '07',
  'Keski-Suomi' => '08',
  'Kymenlaakso' => '09',
  'Lappi' => '10',
  'Paijat-Hame' => '16',
  'Pirkanmaa' => '11',
  'Pohjanmaa' => '12',
  'Pohjois-Karjala' => '13',
  'Pohjois-Pohjanmaa' => '14',
  'Pohjois-Savo' => '15',
  'Satakunta' => '17',
  'Uusimaa' => '18',
  'Varsinais-Suomi' => '19',
);