<?php
 return array (
  'Alta Verapaz' => 'AV',
  'Baja Verapaz' => 'BV',
  'Chimaltenango' => 'CM',
  'Chiquimula' => 'CQ',
  'El Progreso' => 'PR',
  'Escuintla' => 'ES',
  'Guatemala' => 'GU',
  'Huehuetenango' => 'HU',
  'Izabal' => 'IZ',
  'Jalapa' => 'JA',
  'Jutiapa' => 'JU',
  'Peten' => 'PE',
  'Quetzaltenango' => 'QZ',
  'Quiche' => 'QC',
  'Retalhuleu' => 'RE',
  'Sacatepequez' => 'SA',
  'San Marcos' => 'SM',
  'Santa Rosa' => 'SR',
  'Solola' => 'SO',
  'Suchitepequez' => 'SU',
  'Totonicapan' => 'TO',
  'Zacapa' => 'ZA',
);