<?php
 return array (
  'Agana Heights Municipality' => '01',
  'Agat Municipality' => '02',
  'Asan-Maina Municipality' => '03',
  'Barrigada Municipality' => '04',
  'Chalan Pago-Ordot Municipality' => '05',
  'Dededo Municipality' => '06',
  'Hagatna Municipality' => '07',
  'Inarajan Municipality' => '08',
  'Mangilao Municipality' => '09',
  'Merizo Municipality' => '10',
  'Mongmong-Toto-Maite Municipality' => '11',
  'Piti Municipality' => '12',
  'Santa Rita Municipality' => '13',
  'Sinajana Municipality' => '14',
  'Talofofo Municipality' => '15',
  'Tamuning-Tumon-Harmon Municipality' => '16',
  'Umatac Municipality' => '17',
  'Yigo Municipality' => '18',
  'Yona Municipality' => '19',
);