<?php
 return array (
  'Bjelovarsko-bilogorska zupanija' => '07',
  'Brodsko-posavska zupanija' => '12',
  'Dubrovacko-neretvanska zupanija' => '19',
  'Grad Zagreb' => '21',
  'Istarska zupanija' => '18',
  'Karlovacka zupanija' => '04',
  'Koprivnicko-krizevacka zupanija' => '06',
  'Krapinsko-zagorska zupanija' => '02',
  'Licko-senjska zupanija' => '09',
  'Medimurska zupanija' => '20',
  'Osjecko-baranjska zupanija' => '14',
  'Pozesko-slavonska zupanija' => '11',
  'Primorsko-goranska zupanija' => '08',
  'Sibensko-kninska zupanija' => '15',
  'Sisacko-moslavacka zupanija' => '03',
  'Splitsko-dalmatinska zupanija' => '17',
  'Varazdinska zupanija' => '05',
  'Viroviticko-podravska zupanija' => '10',
  'Vukovarsko-srijemska zupanija' => '16',
  'Zadarska zupanija' => '13',
  'Zagrebacka zupanija' => '01',
);