<?php
 return array (
  'Bacs-Kiskun' => 'BK',
  'Baranya' => 'BA',
  'Bekes' => 'BE',
  'Borsod-Abauj-Zemplen' => 'BZ',
  'Budapest' => 'BU',
  'Csongrad' => 'CS',
  'Fejer' => 'FE',
  'Gyor-Moson-Sopron' => 'GS',
  'Hajdu-Bihar' => 'HB',
  'Heves' => 'HE',
  'Jasz-Nagykun-Szolnok' => 'JN',
  'Komarom-Esztergom' => 'KE',
  'Nograd' => 'NO',
  'Pest' => 'PE',
  'Somogy' => 'SO',
  'Szabolcs-Szatmar-Bereg' => 'SZ',
  'Tolna' => 'TO',
  'Vas' => 'VA',
  'Veszprem' => 'VM',
  'Zala' => 'ZA',
);