<?php
 return array (
  'Aceh' => 'AC',
  'Bali' => 'BA',
  'Banten' => 'BT',
  'Bengkulu' => 'BE',
  'Gorontalo' => 'GO',
  'Jakarta Raya' => 'JK',
  'Jambi' => 'JA',
  'Jawa Barat' => 'JB',
  'Jawa Tengah' => 'JT',
  'Jawa Timur' => 'JI',
  'Kalimantan Barat' => 'KB',
  'Kalimantan Selatan' => 'KS',
  'Kalimantan Tengah' => 'KT',
  'Kalimantan Timur' => 'KI',
  'Kepulauan Bangka Belitung' => 'BB',
  'Kepulauan Riau' => 'KR',
  'Lampung' => 'LA',
  'Maluku' => 'ML',
  'Maluku Utara' => 'MU',
  'Nusa Tenggara Barat' => 'NB',
  'Nusa Tenggara Timur' => 'NT',
  'Papua' => 'PP',
  'Papua Barat' => 'PB',
  'Riau' => 'RI',
  'Sulawesi Barat' => 'SR',
  'Sulawesi Selatan' => 'SN',
  'Sulawesi Tengah' => 'ST',
  'Sulawesi Tenggara' => 'SG',
  'Sulawesi Utara' => 'SA',
  'Sumatera Barat' => 'SB',
  'Sumatera Selatan' => 'SS',
  'Sumatera Utara' => 'SU',
  'Yogyakarta' => 'YO',
);