<?php
 return array (
  'Al Anbar' => 'AN',
  'Al Basrah' => 'BA',
  'Al Muthanna' => 'MU',
  'Al Qadisiyah' => 'QA',
  'An Najaf' => 'NA',
  'Arbil' => 'AR',
  'As Sulaymaniyah' => 'SU',
  'Babil' => 'BB',
  'Baghdad' => 'BG',
  'Dahuk' => 'DA',
  'Dhi Qar' => 'DQ',
  'Diyala' => 'DI',
  'Karbala\'' => 'KA',
  'Kirkuk' => 'KI',
  'Maysan' => 'MA',
  'Ninawa' => 'NI',
  'Salah ad Din' => 'SD',
  'Wasit' => 'WA',
);