<?php
 return array (
  'Alborz' => '32',
  'Ardabil' => '03',
  'Azarbayjan-e Gharbi' => '02',
  'Azarbayjan-e Sharqi' => '01',
  'Bushehr' => '06',
  'Chahar Mahal va Bakhtiari' => '08',
  'Esfahan' => '04',
  'Fars' => '14',
  'Gilan' => '19',
  'Golestan' => '27',
  'Hamadan' => '24',
  'Hormozgan' => '23',
  'Ilam' => '05',
  'Kerman' => '15',
  'Kermanshah' => '17',
  'Khorasan-e Jonubi' => '29',
  'Khorasan-e Razavi' => '30',
  'Khorasan-e Shomali' => '31',
  'Khuzestan' => '10',
  'Kohgiluyeh va Bowyer Ahmad' => '18',
  'Kordestan' => '16',
  'Lorestan' => '20',
  'Markazi' => '22',
  'Mazandaran' => '21',
  'Qazvin' => '28',
  'Qom' => '26',
  'Semnan' => '12',
  'Sistan va Baluchestan' => '13',
  'Tehran' => '07',
  'Yazd' => '25',
  'Zanjan' => '11',
);