<?php
 return array (
  'Baat Dambang' => '02',
  'Banteay Mean Chey' => '01',
  'Kampong Chaam' => '03',
  'Kampong Chhnang' => '04',
  'Kampong Spueu' => '05',
  'Kampong Thum' => '06',
  'Kampot' => '07',
  'Kandaal' => '08',
  'Kaoh Kong' => '09',
  'Kracheh' => '10',
  'Krong Kaeb' => '23',
  'Krong Pailin' => '24',
  'Krong Preah Sihanouk' => '18',
  'Mondol Kiri' => '11',
  'Otdar Mean Chey' => '22',
  'Phnom Penh' => '12',
  'Pousaat' => '15',
  'Preah Vihear' => '13',
  'Prey Veaeng' => '14',
  'Rotanak Kiri' => '16',
  'Siem Reab' => '17',
  'Stueng Traeng' => '19',
  'Svaay Rieng' => '20',
  'Taakaev' => '21',
);