<?php
 return array (
  'Al Butnan' => 'BU',
  'Al Jabal al Akhdar' => 'JA',
  'Al Jabal al Gharbi' => 'JG',
  'Al Jafarah' => 'JI',
  'Al Jufrah' => 'JU',
  'Al Kufrah' => 'KF',
  'Al Marj' => 'MJ',
  'Al Marqab' => 'MB',
  'Al Wahat' => 'WA',
  'An Nuqat al Khams' => 'NQ',
  'Az Zawiyah' => 'ZA',
  'Banghazi' => 'BA',
  'Darnah' => 'DR',
  'Ghat' => 'GT',
  'Misratah' => 'MI',
  'Murzuq' => 'MQ',
  'Nalut' => 'NL',
  'Sabha' => 'SB',
  'Surt' => 'SR',
  'Tarabulus' => 'TB',
  'Wadi al Hayat' => 'WD',
  'Wadi ash Shati\'' => 'WS',
);