<?php
 return array (
  'Ailinglaplap' => 'ALL',
  'Ailuk' => 'ALK',
  'Arno' => 'ARN',
  'Aur' => 'AUR',
  'Bikini and Kili' => 'KIL',
  'Ebon' => 'EBO',
  'Enewetak and Ujelang' => 'ENI',
  'Jabat' => 'JAB',
  'Jaluit' => 'JAL',
  'Kwajalein' => 'KWA',
  'Lae' => 'LAE',
  'Lib' => 'LIB',
  'Likiep' => 'LIK',
  'Majuro' => 'MAJ',
  'Maloelap' => 'MAL',
  'Mejit' => 'MEJ',
  'Mili' => 'MIL',
  'Namdrik' => 'NMK',
  'Namu' => 'NMU',
  'Rongelap' => 'RON',
  'Ujae' => 'UJA',
  'Utrik' => 'UTI',
  'Wotho' => 'WTH',
  'Wotje' => 'WTJ',
);