<?php
 return array (
  'Balaka' => 'BA',
  'Blantyre' => 'BL',
  'Chikwawa' => 'CK',
  'Chiradzulu' => 'CR',
  'Chitipa' => 'CT',
  'Dedza' => 'DE',
  'Dowa' => 'DO',
  'Karonga' => 'KR',
  'Kasungu' => 'KS',
  'Likoma' => 'LK',
  'Lilongwe' => 'LI',
  'Machinga' => 'MH',
  'Mangochi' => 'MG',
  'Mchinji' => 'MC',
  'Mulanje' => 'MU',
  'Mwanza' => 'MW',
  'Mzimba' => 'MZ',
  'Neno' => 'NE',
  'Nkhata Bay' => 'NB',
  'Nkhotakota' => 'NK',
  'Nsanje' => 'NS',
  'Ntcheu' => 'NU',
  'Ntchisi' => 'NI',
  'Phalombe' => 'PH',
  'Rumphi' => 'RU',
  'Salima' => 'SA',
  'Thyolo' => 'TH',
  'Zomba' => 'ZO',
);