<?php
 return array (
  'Aguascalientes' => 'AGU',
  'Baja California' => 'BCN',
  'Baja California Sur' => 'BCS',
  'Campeche' => 'CAM',
  'Chiapas' => 'CHP',
  'Chihuahua' => 'CHH',
  'Ciudad de Mexico' => 'CMX',
  'Coahuila de Zaragoza' => 'COA',
  'Colima' => 'COL',
  'Durango' => 'DUR',
  'Guanajuato' => 'GUA',
  'Guerrero' => 'GRO',
  'Hidalgo' => 'HID',
  'Jalisco' => 'JAL',
  'Mexico' => 'MEX',
  'Michoacan de Ocampo' => 'MIC',
  'Morelos' => 'MOR',
  'Nayarit' => 'NAY',
  'Nuevo Leon' => 'NLE',
  'Oaxaca' => 'OAX',
  'Puebla' => 'PUE',
  'Queretaro' => 'QUE',
  'Quintana Roo' => 'ROO',
  'San Luis Potosi' => 'SLP',
  'Sinaloa' => 'SIN',
  'Sonora' => 'SON',
  'Tabasco' => 'TAB',
  'Tamaulipas' => 'TAM',
  'Tlaxcala' => 'TLA',
  'Veracruz de Ignacio de la Llave' => 'VER',
  'Yucatan' => 'YUC',
  'Zacatecas' => 'ZAC',
);