<?php
 return array (
  'Akershus' => '02',
  'Aust-Agder' => '09',
  'Buskerud' => '06',
  'Finnmark' => '20',
  'Hedmark' => '04',
  'Hordaland' => '12',
  'More og Romsdal' => '15',
  'Nord-Trondelag' => '17',
  'Nordland' => '18',
  'Oppland' => '05',
  'Oslo' => '03',
  'Ostfold' => '01',
  'Rogaland' => '11',
  'Sogn og Fjordane' => '14',
  'Sor-Trondelag' => '16',
  'Telemark' => '08',
  'Troms' => '19',
  'Vest-Agder' => '10',
  'Vestfold' => '07',
);