<?php
 return array (
  'Auckland' => 'AUK',
  'Bay of Plenty' => 'BOP',
  'Canterbury' => 'CAN',
  'Chatham Islands Territory' => 'CIT',
  'Gisborne' => 'GIS',
  'Hawke\'s Bay' => 'HKB',
  'Manawatu-Wanganui' => 'MWT',
  'Marlborough' => 'MBH',
  'Nelson' => 'NSN',
  'Northland' => 'NTL',
  'Otago' => 'OTA',
  'Southland' => 'STL',
  'Taranaki' => 'TKI',
  'Tasman' => 'TAS',
  'Waikato' => 'WKO',
  'Wellington' => 'WGN',
  'West Coast' => 'WTC',
);