<?php
 return array (
  'Amazonas' => 'AMA',
  'Ancash' => 'ANC',
  'Apurimac' => 'APU',
  'Arequipa' => 'ARE',
  'Ayacucho' => 'AYA',
  'Cajamarca' => 'CAJ',
  'Cusco' => 'CUS',
  'El Callao' => 'CAL',
  'Huancavelica' => 'HUV',
  'Huanuco' => 'HUC',
  'Ica' => 'ICA',
  'Junin' => 'JUN',
  'La Libertad' => 'LAL',
  'Lambayeque' => 'LAM',
  'Lima' => 'LIM',
  'Loreto' => 'LOR',
  'Madre de Dios' => 'MDD',
  'Moquegua' => 'MOQ',
  'Pasco' => 'PAS',
  'Piura' => 'PIU',
  'Puno' => 'PUN',
  'San Martin' => 'SAM',
  'Tacna' => 'TAC',
  'Tumbes' => 'TUM',
  'Ucayali' => 'UCA',
);