<?php
 return array (
  'Bougainville' => 'NSB',
  'Chimbu' => 'CPK',
  'East New Britain' => 'EBR',
  'East Sepik' => 'ESW',
  'Eastern Highlands' => 'EHG',
  'Enga' => 'EPW',
  'Gulf' => 'GPK',
  'Madang' => 'MPM',
  'Manus' => 'MRL',
  'Milne Bay' => 'MBA',
  'Morobe' => 'MPL',
  'National Capital District (Port Moresby)' => 'NCD',
  'New Ireland' => 'NIK',
  'Northern' => 'NPP',
  'Southern Highlands' => 'SHM',
  'West New Britain' => 'WBK',
  'West Sepik' => 'SAN',
  'Western' => 'WPD',
  'Western Highlands' => 'WHM',
);