<?php
 return array (
  'Aveiro' => '01',
  'Beja' => '02',
  'Braga' => '03',
  'Braganca' => '04',
  'Castelo Branco' => '05',
  'Coimbra' => '06',
  'Evora' => '07',
  'Faro' => '08',
  'Guarda' => '09',
  'Leiria' => '10',
  'Lisboa' => '11',
  'Portalegre' => '12',
  'Porto' => '13',
  'Regiao Autonoma da Madeira' => '30',
  'Regiao Autonoma dos Acores' => '20',
  'Santarem' => '14',
  'Setubal' => '15',
  'Viana do Castelo' => '16',
  'Vila Real' => '17',
  'Viseu' => '18',
);