<?php
 return array (
  'Beograd' => '00',
  'Borski okrug' => '14',
  'Branicevski okrug' => '11',
  'Jablanicki okrug' => '23',
  'Juznobacki okrug' => '06',
  'Juznobanatski okrug' => '04',
  'Kolubarski okrug' => '09',
  'Kosovsko-Mitrovacki okrug' => '28',
  'Macvanski okrug' => '08',
  'Moravicki okrug' => '17',
  'Nisavski okrug' => '20',
  'Pcinjski okrug' => '24',
  'Pecki okrug' => '26',
  'Pirotski okrug' => '22',
  'Podunavski okrug' => '10',
  'Prizrenski okrug' => '27',
  'Rasinski okrug' => '19',
  'Raski okrug' => '18',
  'Severnobacki okrug' => '01',
  'Severnobanatski okrug' => '03',
  'Srednjebanatski okrug' => '02',
  'Sremski okrug' => '07',
  'Sumadijski okrug' => '12',
  'Toplicki okrug' => '21',
  'Zajecarski okrug' => '15',
  'Zapadnobacki okrug' => '05',
  'Zlatiborski okrug' => '16',
);