<?php
 return array (
  'Blekinge lan' => '0K',
  'Dalarnas lan' => '0W',
  'Gavleborgs lan' => '0X',
  'Gotlands lan' => '0I',
  'Hallands lan' => '0N',
  'Jamtlands lan' => '0Z',
  'Jonkopings lan' => '0F',
  'Kalmar lan' => '0H',
  'Kronobergs lan' => '0G',
  'Norrbottens lan' => 'BD',
  'Orebro lan' => '0T',
  'Ostergotlands lan' => '0E',
  'Skane lan' => '0M',
  'Sodermanlands lan' => '0D',
  'Stockholms lan' => 'AB',
  'Uppsala lan' => '0C',
  'Varmlands lan' => '0S',
  'Vasterbottens lan' => 'AC',
  'Vasternorrlands lan' => '0Y',
  'Vastmanlands lan' => '0U',
  'Vastra Gotalands lan' => '0O',
);