<?php
 return array (
  'Bahr el Gazel' => 'BG',
  'Batha' => 'BA',
  'Borkou' => 'BO',
  'Chari-Baguirmi' => 'CB',
  'Guera' => 'GR',
  'Hadjer Lamis' => 'HL',
  'Kanem' => 'KA',
  'Lac' => 'LC',
  'Logone-Occidental' => 'LO',
  'Logone-Oriental' => 'LR',
  'Mandoul' => 'MA',
  'Mayo-Kebbi-Est' => 'ME',
  'Mayo-Kebbi-Ouest' => 'MO',
  'Moyen-Chari' => 'MC',
  'Ouaddai' => 'OD',
  'Salamat' => 'SA',
  'Tandjile' => 'TA',
  'Tibesti' => 'TI',
  'Wadi Fira' => 'WF',
);