<?php
 return array (
  'Beja' => '31',
  'Ben Arous' => '13',
  'Bizerte' => '23',
  'Gabes' => '81',
  'Gafsa' => '71',
  'Jendouba' => '32',
  'Kairouan' => '41',
  'Kasserine' => '42',
  'Kebili' => '73',
  'L\'Ariana' => '12',
  'La Manouba' => '14',
  'Le Kef' => '33',
  'Mahdia' => '53',
  'Medenine' => '82',
  'Monastir' => '52',
  'Nabeul' => '21',
  'Sfax' => '61',
  'Sidi Bouzid' => '43',
  'Siliana' => '34',
  'Sousse' => '51',
  'Tataouine' => '83',
  'Tozeur' => '72',
  'Tunis' => '11',
  'Zaghouan' => '22',
);