<?php
 return array (
  'Changhua' => 'CHA',
  'Chiayi' => 'CYQ',
  'Hsinchu' => 'HSQ',
  'Hualien' => 'HUA',
  'Kaohsiung' => 'KHH',
  'Keelung' => 'KEE',
  'Kinmen' => 'KIN',
  'Lienchiang' => 'LIE',
  'Miaoli' => 'MIA',
  'Nantou' => 'NAN',
  'New Taipei' => 'NWT',
  'Penghu' => 'PEN',
  'Pingtung' => 'PIF',
  'Taichung' => 'TXG',
  'Tainan' => 'TNN',
  'Taipei' => 'TPE',
  'Taitung' => 'TTT',
  'Taoyuan' => 'TAO',
  'Yilan' => 'ILA',
  'Yunlin' => 'YUN',
);