<?php
 return array (
  'Arusha' => '01',
  'Dar es Salaam' => '02',
  'Dodoma' => '03',
  'Iringa' => '04',
  'Kagera' => '05',
  'Kaskazini Pemba' => '06',
  'Kaskazini Unguja' => '07',
  'Kigoma' => '08',
  'Kilimanjaro' => '09',
  'Kusini Pemba' => '10',
  'Kusini Unguja' => '11',
  'Lindi' => '12',
  'Manyara' => '26',
  'Mara' => '13',
  'Mbeya' => '14',
  'Mjini Magharibi' => '15',
  'Morogoro' => '16',
  'Mtwara' => '17',
  'Mwanza' => '18',
  'Pwani' => '19',
  'Rukwa' => '20',
  'Ruvuma' => '21',
  'Shinyanga' => '22',
  'Singida' => '23',
  'Tabora' => '24',
  'Tanga' => '25',
);