<?php
 return array (
  'Avtonomna Respublika Krym' => '43',
  'Cherkaska oblast' => '71',
  'Chernihivska oblast' => '74',
  'Chernivetska oblast' => '77',
  'Dnipropetrovska oblast' => '12',
  'Donetska oblast' => '14',
  'Ivano-Frankivska oblast' => '26',
  'Kharkivska oblast' => '63',
  'Khersonska oblast' => '65',
  'Khmelnytska oblast' => '68',
  'Kirovohradska oblast' => '35',
  'Kyiv' => '30',
  'Kyivska oblast' => '32',
  'Luhanska oblast' => '09',
  'Lvivska oblast' => '46',
  'Mykolaivska oblast' => '48',
  'Odeska oblast' => '51',
  'Poltavska oblast' => '53',
  'Rivnenska oblast' => '56',
  'Sevastopol\'' => '40',
  'Sumska oblast' => '59',
  'Ternopilska oblast' => '61',
  'Vinnytska oblast' => '05',
  'Volynska oblast' => '07',
  'Zakarpatska oblast' => '21',
  'Zaporizka oblast' => '23',
  'Zhytomyrska oblast' => '18',
);