<?php
 return array (
  'Amazonas' => '0Z',
  'Anzoategui' => '0B',
  'Apure' => '0C',
  'Aragua' => '0D',
  'Barinas' => '0E',
  'Bolivar' => '0F',
  'Carabobo' => '0G',
  'Cojedes' => '0H',
  'Delta Amacuro' => '0Y',
  'Distrito Capital' => '0A',
  'Falcon' => '0I',
  'Guarico' => '0J',
  'Lara' => '0K',
  'Merida' => '0L',
  'Miranda' => '0M',
  'Monagas' => '0N',
  'Nueva Esparta' => '0O',
  'Portuguesa' => '0P',
  'Sucre' => '0R',
  'Tachira' => '0S',
  'Trujillo' => '0T',
  'Vargas' => '0X',
  'Yaracuy' => '0U',
  'Zulia' => '0V',
);