<?php
 return array (
  '\'Adan' => 'AD',
  '\'Amran' => 'AM',
  'Abyan' => 'AB',
  'Ad Dali\'' => 'DA',
  'Al Bayda\'' => 'BA',
  'Al Hudaydah' => 'HU',
  'Al Jawf' => 'JA',
  'Al Mahrah' => 'MR',
  'Al Mahwit' => 'MW',
  'Amanat al \'Asimah' => 'SA',
  'Dhamar' => 'DH',
  'Hadramawt' => 'HD',
  'Hajjah' => 'HJ',
  'Ibb' => 'IB',
  'Lahij' => 'LA',
  'Ma\'rib' => 'MA',
  'Raymah' => 'RA',
  'Sa\'dah' => 'SD',
  'San\'a\'' => 'SN',
  'Shabwah' => 'SH',
  'Ta\'izz' => 'TA',
);